version: ' 26.1.1'

services:
  db:
      container_name: 'mysql-db'
      image: 'mysql:latest'
      restart: 'always'
      environment:
        - 'MYSQL_DATABASE=tdinheiro'
        - 'MYSQL_PASSWORD=123'
        - 'MYSQL_ROOT_PASSWORD=123'
        - 'MYSQL_USER=admin'
      ports:
        - '3306:3306'
      networks:
        - minha-rede

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tdinheiro
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tdinheiro
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
    networks:
      - minha-rede

networks:
    minha-rede:
      driver: bridge

